TTK changes for postman interoperability
openMF/ph-ee-testing-toolkit-ui pull request #1
Opened 2023-02-28 21:40 UTC by ramvr1256

2023-03-01 07:08 UTC, fynmanoj requested changes

2023-03-01 07:08 UTC, fynmanoj commented on src/routes.js
> +    //     path: '/monitoring',
remove commented lines

2023-03-01 07:08 UTC, fynmanoj commented on package-lock.json
> -        "core-js": "^3.27.2",
remove generated files
if these changes can be automatically generated

2023-03-01 07:08 UTC, fynmanoj commented on src/views/outbound/EnvironmentManager.jsx
> +                                        //     this.environmentFileSelector.click();
remove commented lines

2023-03-02 11:52 UTC, ramvr1256 commented
Requested Changes are done @fynmanoj Kindly review.

2023-03-09 06:55 UTC, merged